services:
  db:
    image: bitnami/postgresql:13.16.0
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=url_shortener

volumes:
  postgresql_data:
    driver: local